# Generated by Django 3.2 on 2021-08-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='شعبه'),
            preserve_default=False,
        ),
    ]
