# Generated by Django 3.2 on 2021-09-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210701_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('a', 'ادمین سیرجان'), ('b', 'ادمین تهران'), ('c', 'مدیر کل'), ('d', 'مشتری')], default='d', max_length=1),
        ),
    ]
