# Generated by Django 3.2 on 2021-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('2', 'سیرجان'), ('3', 'بندرعباس'), ('4', 'تهران'), ('5', 'رشت'), ('0', 'مدیر'), ('1', 'مشتری')], default='1', max_length=2),
        ),
    ]
