# Generated by Django 3.2 on 2021-09-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210915_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کاربر ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='کاربر مدیر'),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('role', models.CharField(choices=[('0', 'ادمین سیرجان'), ('1', 'ادمین بندرعباس'), ('2', 'ادمین تهران'), ('3', 'ادمین رشت')], max_length=2, verbose_name='نقش')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
