# Generated by Django 3.2 on 2021-10-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210921_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'مدیر شعبه', 'verbose_name_plural': 'مدیران شعب'},
        ),
    ]
