# Generated by Django 3.2 on 2021-10-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0002_email_max_length'),
        ('orders', '0003_order_branch'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('users', '0013_alter_adminuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
