# Generated by Django 3.2 on 2021-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='نام شعبه')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبات',
            },
        ),
    ]
