# Generated by Django 3.2.4 on 2021-07-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_title',
            new_name='product_title',
        ),
    ]
