# Generated by Django 3.2 on 2021-09-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('orders', '0002_auto_20210720_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default='سیرجان', on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='شعبه'),
            preserve_default=False,
        ),
    ]
